/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => RidiculousCodingPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/constants.ts
var DEFAULT_SETTINGS = {
  blips: true,
  explosions: true,
  chars: true,
  shake: true,
  shakeAmplitude: 6,
  sound: true,
  fireworks: true,
  baseXp: 50,
  enableStatusBar: true,
  reducedEffects: false
};
var RATE_LIMITS = {
  BLIP_MS: 20,
  BOOM_MS: 100,
  MAX_DECORATIONS_PER_TYPE: 5,
  MAX_SHAKE_TOTAL_MS: 400,
  SHAKE_FRAME_MS: 50
};
var STATUS_BAR_CLASS = "ridiculous-coding-status-bar";
var PANEL_VIEW_TYPE = "ridiculous-coding-panel";
var FIREWORKS_CLASS = "ridiculous-coding-fireworks";

// src/XPService.ts
var XPService = class {
  constructor(plugin, baseXp) {
    this.xp = 0;
    this.level = 1;
    this.xpLevelStart = 0;
    var _a, _b, _c, _d;
    this.plugin = plugin;
    this.baseXp = baseXp;
    const saved = plugin.settings;
    this.xp = (_a = saved.xp) != null ? _a : 0;
    this.level = (_b = saved.level) != null ? _b : 1;
    this.xpLevelStart = (_c = saved.xpLevelStart) != null ? _c : 0;
    this.xpNextAbs = (_d = saved.xpNextAbs) != null ? _d : 2 * baseXp;
  }
  get progress() {
    const max = this.xpNextAbs - this.xpLevelStart;
    return { current: this.xp - this.xpLevelStart, max: Math.max(1, max) };
  }
  addXp(n) {
    this.xp += n;
    let leveledUp = false;
    if (this.xp >= this.xpNextAbs) {
      this.level += 1;
      this.xpLevelStart = this.xp;
      this.xpNextAbs = this.xp + Math.round(this.baseXp * this.level / 10) * 10;
      leveledUp = true;
    }
    this.save();
    return leveledUp;
  }
  reset() {
    this.level = 1;
    this.xp = 0;
    this.xpLevelStart = 0;
    this.xpNextAbs = 2 * this.baseXp;
    this.save();
  }
  setBaseXp(base) {
    this.baseXp = base;
    if (this.level <= 1 && this.xp === 0) {
      this.xpNextAbs = 2 * this.baseXp;
    } else if (this.xp >= this.xpNextAbs) {
      this.xpNextAbs = this.xp + Math.round(this.baseXp * this.level / 10) * 10;
    }
    this.save();
  }
  save() {
    const data = this.plugin.settings;
    data.xp = this.xp;
    data.level = this.level;
    data.xpNextAbs = this.xpNextAbs;
    data.xpLevelStart = this.xpLevelStart;
    this.plugin.saveSettings();
  }
};

// src/AudioService.ts
var AudioService = class {
  constructor(plugin) {
    this.audioContext = null;
    this.buffers = /* @__PURE__ */ new Map();
    this.isEnabled = true;
    this.plugin = plugin;
  }
  async configure() {
    try {
      this.audioContext = new AudioContext();
      await this.loadSound("blip", "media/sound/blip.wav");
      await this.loadSound("boom", "media/sound/boom.wav");
      await this.loadSound("fireworks", "media/sound/fireworks.wav");
    } catch (e) {
      console.warn("Ridiculous Coding: Audio initialization failed", e);
      this.audioContext = null;
    }
  }
  async loadSound(name, path) {
    if (!this.audioContext)
      return;
    try {
      const response = await fetch(path);
      const arrayBuffer = await response.arrayBuffer();
      const audioBuffer = await this.audioContext.decodeAudioData(arrayBuffer);
      this.buffers.set(name, audioBuffer);
    } catch (e) {
      console.warn(`Ridiculous Coding: Failed to load sound "${name}"`, e);
    }
  }
  play(event) {
    if (!this.isEnabled || !this.audioContext)
      return;
    if (this.audioContext.state === "suspended") {
      this.audioContext.resume();
    }
    let bufferName;
    let playbackRate = 1;
    switch (event.type) {
      case "blip":
        bufferName = "blip";
        playbackRate = event.pitch;
        break;
      case "boom":
        bufferName = "boom";
        break;
      case "fireworks":
        bufferName = "fireworks";
        break;
    }
    const buffer = this.buffers.get(bufferName);
    if (!buffer)
      return;
    const source = this.audioContext.createBufferSource();
    source.buffer = buffer;
    source.playbackRate.value = playbackRate;
    const gainNode = this.audioContext.createGain();
    gainNode.gain.value = bufferName === "fireworks" ? 0.5 : 0.3;
    source.connect(gainNode);
    gainNode.connect(this.audioContext.destination);
    source.start(0);
  }
  dispose() {
    if (this.audioContext) {
      this.audioContext.close();
      this.audioContext = null;
    }
    this.buffers.clear();
  }
};

// src/SettingsTab.ts
var import_obsidian = require("obsidian");
var RidiculousCodingSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin, xpService) {
    super(app, plugin);
    this.plugin = plugin;
    this.xpService = xpService;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Ridiculous Coding" });
    new import_obsidian.Setting(containerEl).setName("Blip effects").setDesc("Show animations when typing characters").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.blips).onChange(async (value) => {
        this.plugin.settings.blips = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Explosion effects").setDesc("Show boom effects when deleting").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.explosions).onChange(async (value) => {
        this.plugin.settings.explosions = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Character labels").setDesc("Overlay the typed character label with effects").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.chars).onChange(async (value) => {
        this.plugin.settings.chars = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Screen shake").setDesc("Enable screen shake effects").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.shake).onChange(async (value) => {
        this.plugin.settings.shake = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Shake amplitude").setDesc("Maximum shake displacement in pixels (0-32)").addSlider(
      (slider) => slider.setLimits(0, 32, 1).setValue(this.plugin.settings.shakeAmplitude).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.shakeAmplitude = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Sound effects").setDesc("Play sounds for blips, booms, and fireworks").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.sound).onChange(async (value) => {
        this.plugin.settings.sound = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Fireworks").setDesc("Celebrate level-ups with fireworks animation").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.fireworks).onChange(async (value) => {
        this.plugin.settings.fireworks = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Base XP").setDesc("Base XP value used in level-up curve (10-200)").addSlider(
      (slider) => slider.setLimits(10, 200, 5).setValue(this.plugin.settings.baseXp).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.baseXp = value;
        this.xpService.setBaseXp(value);
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Status bar").setDesc("Show level and XP progress in the status bar").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableStatusBar).onChange(async (value) => {
        this.plugin.settings.enableStatusBar = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Reduced effects mode").setDesc("Disable all visual effects and sounds for accessibility. XP system still works.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.reducedEffects).onChange(async (value) => {
        var _a, _b;
        this.plugin.settings.reducedEffects = value;
        await this.plugin.saveSettings();
        if (value) {
          (_b = (_a = this.plugin).clearAllDecorations) == null ? void 0 : _b.call(_a);
        }
      })
    );
    containerEl.createEl("hr");
    new import_obsidian.Setting(containerEl).setName("Reset XP").setDesc("Reset your experience points and level back to 1").addButton(
      (button) => button.setButtonText("Reset").setWarning().onClick(() => {
        var _a, _b;
        this.xpService.reset();
        (_b = (_a = this.plugin).updateStatusBar) == null ? void 0 : _b.call(_a);
        button.setButtonText("Reset \u2713");
        setTimeout(() => button.setButtonText("Reset"), 2e3);
      })
    );
  }
};

// src/ControlPanel.ts
var import_obsidian2 = require("obsidian");
var RidiculousCodingPanel = class extends import_obsidian2.ItemView {
  constructor(leaf, xpService, settings, onToggle, onResetXp) {
    super(leaf);
    this.xpService = xpService;
    this.settings = settings;
    this.onToggle = onToggle;
    this.onResetXp = onResetXp;
  }
  getViewType() {
    return PANEL_VIEW_TYPE;
  }
  getDisplayText() {
    return "Ridiculous Coding";
  }
  getIcon() {
    return "rocket";
  }
  async onOpen() {
    this.render();
  }
  render() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("ridiculous-coding-panel");
    const header = container.createEl("h3", { text: `\u{1F680} Level ${this.xpService.level}` });
    const prog = this.xpService.progress;
    const progressContainer = container.createDiv({ cls: "progress-bar" });
    const progressFill = progressContainer.createDiv({ cls: "progress-bar-fill" });
    progressFill.style.width = `${prog.current / prog.max * 100}%`;
    const xpText = container.createDiv({ cls: "xp-text" });
    xpText.setText(`${prog.current} / ${prog.max} XP`);
    container.createEl("hr");
    this.addToggle(container, "Blips", this.settings.blips, (v) => {
      this.settings.blips = v;
      this.onToggle("blips", v);
    });
    this.addToggle(container, "Explosions", this.settings.explosions, (v) => {
      this.settings.explosions = v;
      this.onToggle("explosions", v);
    });
    this.addToggle(container, "Shake", this.settings.shake, (v) => {
      this.settings.shake = v;
      this.onToggle("shake", v);
    });
    this.addToggle(container, "Sound", this.settings.sound, (v) => {
      this.settings.sound = v;
      this.onToggle("sound", v);
    });
    this.addToggle(container, "Reduced Effects", this.settings.reducedEffects, (v) => {
      this.settings.reducedEffects = v;
      this.onToggle("reducedEffects", v);
    });
    container.createEl("hr");
    const resetBtn = container.createEl("button", { text: "Reset XP" });
    resetBtn.addEventListener("click", () => {
      this.onResetXp();
      this.render();
    });
  }
  addToggle(container, label, value, onChange) {
    const row = container.createDiv({ cls: "toggle-row" });
    row.createSpan({ text: label });
    const toggle = row.createEl("input", { type: "checkbox" });
    toggle.checked = value;
    toggle.addEventListener("change", () => {
      onChange(toggle.checked);
    });
  }
  refresh() {
    this.render();
  }
  async onClose() {
  }
};

// src/Fireworks.ts
var Fireworks = class {
  constructor() {
    this.canvas = null;
    this.ctx = null;
    this.particles = [];
    this.animId = null;
    this.container = null;
    this.animate = () => {
      if (!this.ctx || !this.canvas)
        return;
      this.ctx.clearRect(0, 0, this.canvas.width, this.canvas.height);
      this.particles = this.particles.filter((p) => {
        p.x += p.vx;
        p.y += p.vy;
        p.vy += 0.05;
        p.vx *= 0.98;
        p.life++;
        if (p.life >= p.maxLife)
          return false;
        const alpha = 1 - p.life / p.maxLife;
        this.ctx.globalAlpha = alpha;
        this.ctx.fillStyle = p.color;
        this.ctx.beginPath();
        this.ctx.arc(p.x, p.y, p.size * alpha, 0, Math.PI * 2);
        this.ctx.fill();
        return true;
      });
      if (this.particles.length > 0) {
        this.animId = requestAnimationFrame(this.animate);
      } else {
        this.hide();
      }
    };
  }
  show() {
    if (this.container)
      return;
    this.container = document.createElement("div");
    this.container.className = FIREWORKS_CLASS;
    this.canvas = document.createElement("canvas");
    this.canvas.style.width = "100%";
    this.canvas.style.height = "100%";
    this.container.appendChild(this.canvas);
    document.body.appendChild(this.container);
    this.canvas.width = window.innerWidth;
    this.canvas.height = window.innerHeight;
    this.ctx = this.canvas.getContext("2d");
    this.spawnBurst(window.innerWidth * 0.3, window.innerHeight * 0.3);
    this.spawnBurst(window.innerWidth * 0.7, window.innerHeight * 0.2);
    this.spawnBurst(window.innerWidth * 0.5, window.innerHeight * 0.4);
    this.animate();
    setTimeout(() => this.hide(), 3e3);
  }
  spawnBurst(x, y) {
    const colors = ["#ff6b6b", "#feca57", "#48dbfb", "#ff9ff3", "#54a0ff", "#5f27cd"];
    const color = colors[Math.floor(Math.random() * colors.length)];
    for (let i = 0; i < 40; i++) {
      const angle = Math.PI * 2 * i / 40 + (Math.random() - 0.5) * 0.3;
      const speed = 2 + Math.random() * 4;
      this.particles.push({
        x,
        y,
        vx: Math.cos(angle) * speed,
        vy: Math.sin(angle) * speed,
        life: 0,
        maxLife: 40 + Math.random() * 30,
        color,
        size: 2 + Math.random() * 3
      });
    }
  }
  hide() {
    if (this.animId !== null) {
      cancelAnimationFrame(this.animId);
      this.animId = null;
    }
    this.particles = [];
    if (this.container) {
      this.container.remove();
      this.container = null;
    }
    this.canvas = null;
    this.ctx = null;
  }
  dispose() {
    this.hide();
  }
};

// src/EffectManager.ts
var import_view = require("@codemirror/view");
var FloatingLabelWidget = class extends import_view.WidgetType {
  constructor(text, color, fontSize = 18) {
    super();
    this.text = text;
    this.color = color;
    this.fontSize = fontSize;
  }
  toDOM(view) {
    const span = document.createElement("span");
    span.className = "rc-floating-label";
    span.textContent = this.text;
    span.style.color = this.color;
    span.style.fontSize = `${this.fontSize}px`;
    span.style.fontWeight = "bold";
    span.style.fontFamily = "monospace";
    span.style.position = "absolute";
    span.style.pointerEvents = "none";
    span.style.zIndex = "1000";
    const prefersReducedMotion = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    if (prefersReducedMotion) {
      span.style.opacity = "0.8";
      setTimeout(() => span.remove(), 300);
    } else {
      span.style.transform = "translateY(-1.1em) scale(1.6)";
      span.style.transformOrigin = "left bottom";
      span.style.transition = "transform 0.4s ease-out, opacity 0.4s ease-out";
      requestAnimationFrame(() => {
        span.style.transform = "translateY(-2.5em) scale(1.0)";
        span.style.opacity = "0";
      });
      setTimeout(() => span.remove(), 450);
    }
    return span;
  }
};
var IconWidget = class extends import_view.WidgetType {
  constructor(iconName) {
    super();
    this.iconName = iconName;
  }
  toDOM(view) {
    const span = document.createElement("span");
    span.className = `rc-icon rc-icon-${this.iconName}`;
    span.style.display = "inline-block";
    span.style.height = "1em";
    span.style.position = "relative";
    span.style.pointerEvents = "none";
    return span;
  }
};
var RidiculousViewPlugin = class {
  constructor(view, settings) {
    this.decorations = import_view.Decoration.none;
    this.pendingEffects = [];
    this.animFrameId = null;
    this.lastBlipTime = 0;
    this.lastBoomTime = 0;
    this.shakeEndAt = 0;
    this.shakeTimerId = null;
    this.shakeDOM = null;
    this.view = view;
    this.settings = settings;
  }
  // Color generation matching the Godot original
  static randomGodotColor() {
    const r = Math.min(255, Math.round(Math.random() * 510));
    const g = Math.min(255, Math.round(Math.random() * 510));
    const b = Math.min(255, Math.round(Math.random() * 510));
    return `rgb(${Math.min(255, r)}, ${Math.min(255, g)}, ${Math.min(255, b)})`;
  }
  update(update) {
    if (!update.docChanged)
      return;
    for (const tr of update.transactions) {
      tr.changes.iterChanges(
        (fromA, toA, _fromB, toB, inserted) => {
          const insertedText = inserted.toString();
          const removedLength = toA - fromA;
          if (insertedText.length > 0 && !this.settings.reducedEffects) {
            this.handleInsert(toB, insertedText);
          }
          if (removedLength > 0 && !this.settings.reducedEffects) {
            this.handleDelete(fromA);
          }
        }
      );
    }
  }
  pendingCount(type) {
    return this.pendingEffects.filter((e) => e.type === type).length;
  }
  handleInsert(pos, text) {
    const now = Date.now();
    if (now - this.lastBlipTime < RATE_LIMITS.BLIP_MS)
      return;
    this.lastBlipTime = now;
    if (text.includes("\n") && this.settings.blips && this.pendingCount("newline") < RATE_LIMITS.MAX_DECORATIONS_PER_TYPE) {
      this.pendingEffects.push({ type: "newline", pos });
    }
    if (this.settings.blips && this.pendingCount("blip") < RATE_LIMITS.MAX_DECORATIONS_PER_TYPE) {
      const charLabel = this.settings.chars ? this.sanitizeLabel(text[0]) : void 0;
      this.pendingEffects.push({ type: "blip", pos, charLabel });
    }
    this.scheduleAnimation();
    if (this.settings.shake) {
      this.triggerShake(text.includes("\n") ? 140 : 120);
    }
  }
  handleDelete(pos) {
    const now = Date.now();
    if (now - this.lastBoomTime < RATE_LIMITS.BOOM_MS)
      return;
    this.lastBoomTime = now;
    if (this.settings.explosions && this.pendingCount("boom") < RATE_LIMITS.MAX_DECORATIONS_PER_TYPE) {
      const charLabel = this.settings.chars ? "BACKSPACE" : void 0;
      this.pendingEffects.push({ type: "boom", pos, charLabel });
    }
    this.scheduleAnimation();
    if (this.settings.shake) {
      this.triggerShake(180);
    }
  }
  scheduleAnimation() {
    if (this.animFrameId !== null)
      return;
    this.animFrameId = requestAnimationFrame(() => this.applyEffects());
  }
  applyEffects() {
    this.animFrameId = null;
    if (this.pendingEffects.length === 0)
      return;
    const decorations = [];
    for (const effect of this.pendingEffects) {
      const pos = Math.min(effect.pos, this.view.state.doc.length);
      if (pos >= this.view.state.doc.length)
        continue;
      const cursorPos = pos;
      switch (effect.type) {
        case "blip": {
          const color = RidiculousViewPlugin.randomGodotColor();
          if (effect.charLabel && this.settings.chars) {
            const widget = new FloatingLabelWidget(effect.charLabel, color);
            decorations.push(
              import_view.Decoration.widget({ widget, side: 1 }).range(cursorPos, cursorPos)
            );
          }
          const iconWidget = new IconWidget("blip");
          decorations.push(
            import_view.Decoration.widget({ widget: iconWidget, side: 1 }).range(cursorPos, cursorPos)
          );
          break;
        }
        case "boom": {
          if (effect.charLabel && this.settings.chars) {
            const color = RidiculousViewPlugin.randomGodotColor();
            const widget = new FloatingLabelWidget(effect.charLabel, color);
            decorations.push(
              import_view.Decoration.widget({ widget, side: 1 }).range(cursorPos, cursorPos)
            );
          }
          const iconWidget = new IconWidget("boom");
          decorations.push(
            import_view.Decoration.widget({ widget: iconWidget, side: 1 }).range(cursorPos, cursorPos)
          );
          break;
        }
        case "newline": {
          const iconWidget = new IconWidget("newline");
          decorations.push(
            import_view.Decoration.widget({ widget: iconWidget, side: -1 }).range(pos, pos)
          );
          break;
        }
      }
    }
    this.decorations = import_view.Decoration.set(decorations);
    this.pendingEffects = [];
    setTimeout(() => {
      this.decorations = import_view.Decoration.none;
      this.view.dispatch();
    }, 400);
  }
  // ── Screen Shake ──
  triggerShake(extendMs) {
    if (!this.settings.shake)
      return;
    const now = Date.now();
    const maxEnd = now + RATE_LIMITS.MAX_SHAKE_TOTAL_MS;
    this.shakeEndAt = Math.min(
      Math.max(this.shakeEndAt, now + extendMs),
      maxEnd
    );
    if (!this.shakeDOM) {
      this.shakeDOM = this.view.scrollDOM;
    }
    if (this.shakeTimerId === null) {
      this.startShakeLoop();
    }
  }
  startShakeLoop() {
    const tick = () => {
      const now = Date.now();
      if (now >= this.shakeEndAt) {
        this.shakeTimerId = null;
        if (this.shakeDOM) {
          this.shakeDOM.style.transform = "";
        }
        return;
      }
      const amplitude = this.settings.shakeAmplitude;
      const angle = Math.random() * Math.PI * 2;
      const dx = Math.round(Math.cos(angle) * amplitude);
      const dy = Math.round(Math.sin(angle) * amplitude);
      if (this.shakeDOM) {
        this.shakeDOM.style.transform = `translate(${dx}px, ${dy}px)`;
        this.shakeDOM.style.transition = "transform 0.03s linear";
      }
      this.shakeTimerId = window.setTimeout(tick, RATE_LIMITS.SHAKE_FRAME_MS);
    };
    tick();
  }
  sanitizeLabel(ch) {
    if (ch === "\n")
      return "";
    if (ch === "	")
      return "\u21B9";
    if (ch.trim() === "")
      return "SPACE";
    return ch;
  }
  clearDecorations() {
    this.decorations = import_view.Decoration.none;
    this.pendingEffects = [];
    if (this.animFrameId !== null) {
      cancelAnimationFrame(this.animFrameId);
      this.animFrameId = null;
    }
    if (this.shakeTimerId !== null) {
      clearTimeout(this.shakeTimerId);
      this.shakeTimerId = null;
    }
    if (this.shakeDOM) {
      this.shakeDOM.style.transform = "";
    }
  }
  destroy() {
    this.clearDecorations();
  }
};
var activeInstances = /* @__PURE__ */ new Set();
function clearActiveDecorations() {
  for (const inst of activeInstances) {
    inst.clearDecorations();
  }
}
function createRidiculousPlugin(settings) {
  class RidiculousPluginAdapter extends RidiculousViewPlugin {
    constructor(view) {
      super(view, settings);
      activeInstances.add(this);
    }
    destroy() {
      super.destroy();
      activeInstances.delete(this);
    }
  }
  return import_view.ViewPlugin.fromClass(RidiculousPluginAdapter, {
    decorations: (p) => p.decorations
  });
}

// src/main.ts
var RidiculousCodingPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.statusBarItem = null;
    this.panel = null;
  }
  async onload() {
    await this.loadSettings();
    this.xpService = new XPService(this, this.settings.baseXp);
    this.audioService = new AudioService(this);
    this.fireworks = new Fireworks();
    await this.audioService.configure();
    this.registerCodeMirrorPlugin();
    this.registerEditorEvents();
    this.statusBarItem = this.addStatusBarItem();
    this.statusBarItem.addClass(STATUS_BAR_CLASS);
    this.statusBarItem.onclick = () => {
      this.activatePanel();
    };
    this.updateStatusBar();
    this.addRibbonIcon("rocket", "Ridiculous Coding", () => this.activatePanel());
    this.addSettingTab(new RidiculousCodingSettingTab(this.app, this, this.xpService));
    this.registerView(PANEL_VIEW_TYPE, (leaf) => {
      this.panel = new RidiculousCodingPanel(
        leaf,
        this.xpService,
        this.settings,
        (key, value) => {
          this.settings[key] = value;
          this.saveSettings();
        },
        () => {
          this.xpService.reset();
          this.updateStatusBar();
        }
      );
      return this.panel;
    });
    this.addCommand({
      id: "show-panel",
      name: "Show Ridiculous Coding Panel",
      callback: () => this.activatePanel()
    });
    this.addCommand({
      id: "reset-xp",
      name: "Reset XP",
      callback: () => {
        this.xpService.reset();
        this.updateStatusBar();
        if (this.panel)
          this.panel.refresh();
      }
    });
  }
  registerCodeMirrorPlugin() {
    const cmExtension = createRidiculousPlugin(this.settings);
    this.registerEditorExtension(cmExtension);
  }
  registerEditorEvents() {
    this.registerEvent(
      this.app.workspace.on("editor-change", (_editor, _info) => {
        const leveledUp = this.xpService.addXp(1);
        this.updateStatusBar();
        if (this.panel)
          this.panel.refresh();
        if (!this.settings.reducedEffects && this.settings.sound) {
          this.audioService.play({ type: "blip", pitch: 1 });
        }
        if (leveledUp && !this.settings.reducedEffects && this.settings.fireworks) {
          this.fireworks.show();
          this.audioService.play({ type: "fireworks" });
        }
      })
    );
  }
  async activatePanel() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(PANEL_VIEW_TYPE)[0];
    if (!leaf) {
      const rightLeaf = workspace.getRightLeaf(false);
      if (!rightLeaf)
        return;
      leaf = rightLeaf;
      await leaf.setViewState({ type: PANEL_VIEW_TYPE, active: true });
    }
    workspace.revealLeaf(leaf);
  }
  updateStatusBar() {
    if (!this.settings.enableStatusBar || !this.statusBarItem)
      return;
    const prog = this.xpService.progress;
    this.statusBarItem.setText(`RC Lv ${this.xpService.level} \u2014 ${prog.current}/${prog.max} XP`);
    this.statusBarItem.setAttr("aria-label", `Ridiculous Coding - Level ${this.xpService.level}`);
  }
  clearAllDecorations() {
    clearActiveDecorations();
  }
  async loadSettings() {
    const saved = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, saved);
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.xpService.setBaseXp(this.settings.baseXp);
    this.audioService.isEnabled = this.settings.sound;
    this.updateStatusBar();
    if (this.panel)
      this.panel.refresh();
  }
  onunload() {
    this.clearAllDecorations();
    this.audioService.dispose();
    this.fireworks.dispose();
    this.app.workspace.detachLeavesOfType(PANEL_VIEW_TYPE);
    this.panel = null;
  }
};
