/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => RidiculousCodingPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/constants.ts
var DEFAULT_SETTINGS = {
  blips: true,
  explosions: true,
  chars: true,
  shake: true,
  shakeAmplitude: 6,
  shakeDecayMs: 120,
  sound: true,
  fireworks: true,
  baseXp: 50,
  enableStatusBar: true,
  reducedEffects: false
};
var RATE_LIMITS = {
  BLIP_MS: 20,
  BOOM_MS: 100,
  MAX_DECORATIONS_PER_TYPE: 5,
  MAX_SHAKE_TOTAL_MS: 400,
  SHAKE_FRAME_MS: 50
};
var PLUGIN_ID = "ridiculous-coding";
var STATUS_BAR_CLASS = "ridiculous-coding-status-bar";
var PANEL_VIEW_TYPE = "ridiculous-coding-panel";
var FIREWORKS_CLASS = "ridiculous-coding-fireworks";

// src/XPService.ts
var XPService = class {
  constructor(plugin, baseXp) {
    this.xp = 0;
    this.level = 1;
    this.xpLevelStart = 0;
    var _a, _b, _c, _d;
    this.plugin = plugin;
    this.baseXp = baseXp;
    const saved = plugin.settings;
    this.xp = (_a = saved.xp) != null ? _a : 0;
    this.level = (_b = saved.level) != null ? _b : 1;
    this.xpLevelStart = (_c = saved.xpLevelStart) != null ? _c : 0;
    this.xpNextAbs = (_d = saved.xpNextAbs) != null ? _d : 2 * baseXp;
  }
  get progress() {
    const max = this.xpNextAbs - this.xpLevelStart;
    return { current: this.xp - this.xpLevelStart, max: Math.max(1, max) };
  }
  addXp(n) {
    this.xp += n;
    let leveledUp = false;
    if (this.xp >= this.xpNextAbs) {
      this.level += 1;
      this.xpLevelStart = this.xp;
      this.xpNextAbs = this.xp + Math.round(this.baseXp * this.level / 10) * 10;
      leveledUp = true;
    }
    this.save();
    return leveledUp;
  }
  reset() {
    this.level = 1;
    this.xp = 0;
    this.xpLevelStart = 0;
    this.xpNextAbs = 2 * this.baseXp;
    this.save();
  }
  setBaseXp(base) {
    this.baseXp = base;
    if (this.level <= 1 && this.xp === 0) {
      this.xpNextAbs = 2 * this.baseXp;
    } else if (this.xp >= this.xpNextAbs) {
      this.xpNextAbs = this.xp + Math.round(this.baseXp * this.level / 10) * 10;
    }
    this.save();
  }
  save() {
    const data = this.plugin.settings;
    data.xp = this.xp;
    data.level = this.level;
    data.xpNextAbs = this.xpNextAbs;
    data.xpLevelStart = this.xpLevelStart;
    void this.plugin.saveSettings();
  }
};

// src/AudioService.ts
var import_obsidian = require("obsidian");
var AudioService = class {
  constructor(app) {
    this.audioContext = null;
    this.buffers = /* @__PURE__ */ new Map();
    this.isEnabled = true;
    this.app = app;
  }
  async configure() {
    try {
      this.audioContext = new AudioContext();
      await this.loadSound("blip", "media/sound/blip.wav");
      await this.loadSound("boom", "media/sound/boom.wav");
      await this.loadSound("fireworks", "media/sound/fireworks.wav");
    } catch (e) {
      console.warn("Ridiculous Coding: Audio initialization failed", e);
      this.audioContext = null;
    }
  }
  async loadSound(name, relativePath) {
    if (!this.audioContext)
      return;
    try {
      const vaultPath = `.obsidian/plugins/${PLUGIN_ID}/${relativePath}`;
      const resourceUrl = this.app.vault.adapter.getResourcePath(vaultPath);
      const response = await (0, import_obsidian.requestUrl)({ url: resourceUrl });
      const arrayBuffer = response.arrayBuffer;
      const audioBuffer = await this.audioContext.decodeAudioData(arrayBuffer);
      this.buffers.set(name, audioBuffer);
    } catch (e) {
      console.warn(`Ridiculous Coding: Failed to load sound "${name}"`, e);
    }
  }
  play(event) {
    if (!this.isEnabled || !this.audioContext)
      return;
    if (this.audioContext.state === "suspended") {
      void this.audioContext.resume();
    }
    let bufferName;
    let playbackRate = 1;
    switch (event.type) {
      case "blip":
        bufferName = "blip";
        playbackRate = event.pitch;
        break;
      case "boom":
        bufferName = "boom";
        break;
      case "fireworks":
        bufferName = "fireworks";
        break;
    }
    const buffer = this.buffers.get(bufferName);
    if (!buffer)
      return;
    const source = this.audioContext.createBufferSource();
    source.buffer = buffer;
    source.playbackRate.value = playbackRate;
    const gainNode = this.audioContext.createGain();
    gainNode.gain.value = bufferName === "fireworks" ? 0.5 : 0.3;
    source.connect(gainNode);
    gainNode.connect(this.audioContext.destination);
    source.start(0);
  }
  dispose() {
    if (this.audioContext) {
      void this.audioContext.close();
      this.audioContext = null;
    }
    this.buffers.clear();
  }
};

// src/SettingsTab.ts
var import_obsidian2 = require("obsidian");
var RidiculousCodingSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin, xpService) {
    super(app, plugin);
    this.plugin = plugin;
    this.xpService = xpService;
  }
  getSettingDefinitions() {
    return [];
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName("Blip effects").setDesc("Show animations when typing characters").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.blips).onChange(async (value) => {
        this.plugin.settings.blips = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Explosion effects").setDesc("Show boom effects when deleting").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.explosions).onChange(async (value) => {
        this.plugin.settings.explosions = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Character labels").setDesc("Overlay the typed character label with effects").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.chars).onChange(async (value) => {
        this.plugin.settings.chars = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Screen shake").setDesc("Enable screen shake effects").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.shake).onChange(async (value) => {
        this.plugin.settings.shake = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Shake amplitude").setDesc("Maximum shake displacement in pixels (0-32)").addSlider(
      (slider) => slider.setLimits(0, 32, 1).setValue(this.plugin.settings.shakeAmplitude).onChange(async (value) => {
        this.plugin.settings.shakeAmplitude = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Shake decay (ms)").setDesc("Minimum shake duration in milliseconds (20-2000)").addSlider(
      (slider) => slider.setLimits(20, 2e3, 20).setValue(this.plugin.settings.shakeDecayMs).onChange(async (value) => {
        this.plugin.settings.shakeDecayMs = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Sound effects").setDesc("Play sounds for blips, booms, and fireworks").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.sound).onChange(async (value) => {
        this.plugin.settings.sound = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Fireworks").setDesc("Celebrate level-ups with fireworks animation").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.fireworks).onChange(async (value) => {
        this.plugin.settings.fireworks = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Base XP").setDesc("Base XP value used in level-up curve (10-200)").addSlider(
      (slider) => slider.setLimits(10, 200, 5).setValue(this.plugin.settings.baseXp).onChange(async (value) => {
        this.plugin.settings.baseXp = value;
        this.xpService.setBaseXp(value);
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Status bar").setDesc("Show level and XP progress in the status bar").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableStatusBar).onChange(async (value) => {
        this.plugin.settings.enableStatusBar = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Reduced effects mode").setDesc("Disable all visual effects and sounds for accessibility. XP system still works.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.reducedEffects).onChange(async (value) => {
        this.plugin.settings.reducedEffects = value;
        await this.plugin.saveSettings();
        if (value) {
          this.plugin.clearAllDecorations();
        }
      })
    );
    containerEl.createEl("hr");
    new import_obsidian2.Setting(containerEl).setName("Reset XP").setDesc("Reset your experience points and level back to 1").addButton(
      (button) => button.setButtonText("Reset").setWarning().onClick(() => {
        this.xpService.reset();
        this.plugin.updateStatusBar();
        button.setButtonText("Reset \u2713");
        window.setTimeout(() => button.setButtonText("Reset"), 2e3);
      })
    );
  }
};

// src/ControlPanel.ts
var import_obsidian3 = require("obsidian");
var RidiculousCodingPanel = class extends import_obsidian3.ItemView {
  constructor(leaf, xpService, settings, onToggle, onResetXp) {
    super(leaf);
    this.xpService = xpService;
    this.settings = settings;
    this.onToggle = onToggle;
    this.onResetXp = onResetXp;
  }
  getViewType() {
    return PANEL_VIEW_TYPE;
  }
  getDisplayText() {
    return "Ridiculous Coding";
  }
  getIcon() {
    return "rocket";
  }
  async onOpen() {
    this.render();
  }
  render() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("ridiculous-coding-panel");
    container.createEl("h3", { text: `\u{1F680} Level ${this.xpService.level}` });
    const prog = this.xpService.progress;
    const progressContainer = container.createDiv({ cls: "progress-bar" });
    const progressFill = progressContainer.createDiv({ cls: "progress-bar-fill" });
    progressFill.style.width = `${prog.current / prog.max * 100}%`;
    const xpText = container.createDiv({ cls: "xp-text" });
    xpText.setText(`${prog.current} / ${prog.max} XP`);
    container.createEl("hr");
    this.addToggle(container, "Blips", this.settings.blips, (v) => {
      this.settings.blips = v;
      this.onToggle("blips", v);
    });
    this.addToggle(container, "Explosions", this.settings.explosions, (v) => {
      this.settings.explosions = v;
      this.onToggle("explosions", v);
    });
    this.addToggle(container, "Shake", this.settings.shake, (v) => {
      this.settings.shake = v;
      this.onToggle("shake", v);
    });
    this.addToggle(container, "Sound", this.settings.sound, (v) => {
      this.settings.sound = v;
      this.onToggle("sound", v);
    });
    this.addToggle(container, "Reduced Effects", this.settings.reducedEffects, (v) => {
      this.settings.reducedEffects = v;
      this.onToggle("reducedEffects", v);
    });
    container.createEl("hr");
    const resetBtn = container.createEl("button", { text: "Reset XP" });
    resetBtn.addEventListener("click", () => {
      this.onResetXp();
      this.render();
    });
  }
  addToggle(container, label, value, onChange) {
    const row = container.createDiv({ cls: "toggle-row" });
    row.createSpan({ text: label });
    const toggle = row.createEl("input", { type: "checkbox" });
    toggle.checked = value;
    toggle.addEventListener("change", () => {
      onChange(toggle.checked);
    });
  }
  refresh() {
    this.render();
  }
  async onClose() {
  }
};

// src/Fireworks.ts
var Fireworks = class {
  constructor() {
    this.canvas = null;
    this.ctx = null;
    this.particles = [];
    this.animId = null;
    this.container = null;
    this.animate = () => {
      if (!this.ctx || !this.canvas)
        return;
      this.ctx.clearRect(0, 0, this.canvas.width, this.canvas.height);
      this.particles = this.particles.filter((p) => {
        p.x += p.vx;
        p.y += p.vy;
        p.vy += 0.05;
        p.vx *= 0.98;
        p.life++;
        if (p.life >= p.maxLife)
          return false;
        const alpha = 1 - p.life / p.maxLife;
        this.ctx.globalAlpha = alpha;
        this.ctx.fillStyle = p.color;
        this.ctx.beginPath();
        this.ctx.arc(p.x, p.y, p.size * alpha, 0, Math.PI * 2);
        this.ctx.fill();
        return true;
      });
      if (this.particles.length > 0) {
        this.animId = window.requestAnimationFrame(this.animate);
      } else {
        this.hide();
      }
    };
  }
  show() {
    if (this.container)
      return;
    this.container = document.body.createEl("div", { cls: FIREWORKS_CLASS });
    this.canvas = this.container.createEl("canvas");
    this.canvas.setCssProps({ width: "100%", height: "100%" });
    this.canvas.width = window.innerWidth;
    this.canvas.height = window.innerHeight;
    this.ctx = this.canvas.getContext("2d");
    this.spawnBurst(window.innerWidth * 0.3, window.innerHeight * 0.3);
    this.spawnBurst(window.innerWidth * 0.7, window.innerHeight * 0.2);
    this.spawnBurst(window.innerWidth * 0.5, window.innerHeight * 0.4);
    this.animate();
    window.setTimeout(() => this.hide(), 3e3);
  }
  spawnBurst(x, y) {
    const colors = ["#ff6b6b", "#feca57", "#48dbfb", "#ff9ff3", "#54a0ff", "#5f27cd"];
    const color = colors[Math.floor(Math.random() * colors.length)];
    for (let i = 0; i < 40; i++) {
      const angle = Math.PI * 2 * i / 40 + (Math.random() - 0.5) * 0.3;
      const speed = 2 + Math.random() * 4;
      this.particles.push({
        x,
        y,
        vx: Math.cos(angle) * speed,
        vy: Math.sin(angle) * speed,
        life: 0,
        maxLife: 40 + Math.random() * 30,
        color,
        size: 2 + Math.random() * 3
      });
    }
  }
  hide() {
    if (this.animId !== null) {
      window.cancelAnimationFrame(this.animId);
      this.animId = null;
    }
    this.particles = [];
    if (this.container) {
      this.container.remove();
      this.container = null;
    }
    this.canvas = null;
    this.ctx = null;
  }
  dispose() {
    this.hide();
  }
};

// src/EffectManager.ts
var import_view = require("@codemirror/view");
var import_obsidian4 = require("obsidian");
var lastEditWasDelete = false;
function wasLastEditDelete() {
  return lastEditWasDelete;
}
var fontBase64 = null;
function setFontBase64(b64) {
  fontBase64 = b64;
}
var spriteDataCache = /* @__PURE__ */ new Map();
async function loadSpriteData(app, kind) {
  if (spriteDataCache.has(kind))
    return;
  const tscnPath = app.vault.adapter.getResourcePath(
    `.obsidian/plugins/${PLUGIN_ID}/media/animations/${kind}.tscn`
  );
  const pngPath = app.vault.adapter.getResourcePath(
    `.obsidian/plugins/${PLUGIN_ID}/media/animations/${kind}.png`
  );
  const [tscnResp, pngResp] = await Promise.all([
    (0, import_obsidian4.requestUrl)({ url: tscnPath }),
    (0, import_obsidian4.requestUrl)({ url: pngPath })
  ]);
  const tscnText = tscnResp.text;
  const pngBytes = new Uint8Array(pngResp.arrayBuffer);
  let binary = "";
  for (let i = 0; i < pngBytes.length; i++) {
    binary += String.fromCharCode(pngBytes[i]);
  }
  const pngB64 = btoa(binary);
  const atlasMap = /* @__PURE__ */ new Map();
  const atlasBlocks = [...tscnText.matchAll(/\[sub_resource\s+type="AtlasTexture"\s+id="(.*?)"\][\s\S]*?region\s*=\s*Rect2\(([^\)]*)\)/g)];
  for (const m of atlasBlocks) {
    const id = m[1];
    const nums = m[2].split(",").map((s) => parseFloat(s.trim()));
    if (nums.length >= 4)
      atlasMap.set(id, { x: nums[0], y: nums[1], w: nums[2], h: nums[3] });
  }
  const framesOrder = [];
  const animBlock = tscnText.match(/\[sub_resource\s+type="SpriteFrames"[\s\S]*?animations\s*=\s*\[(\{[\s\S]*?\})\][\s\S]*?\n/);
  if (animBlock) {
    const block = animBlock[1];
    const subResRefs = [...block.matchAll(/SubResource\("(.*?)"\)/g)];
    for (const sr of subResRefs)
      framesOrder.push(sr[1]);
  }
  const speedMatch = tscnText.match(/"speed"\s*:\s*([0-9.]+)/);
  const fps = speedMatch ? Math.max(1, parseFloat(speedMatch[1])) : 24;
  const frames = [];
  for (const id of framesOrder) {
    const rect = atlasMap.get(id);
    if (rect)
      frames.push(rect);
  }
  if (!frames.length && atlasMap.size)
    frames.push(...[...atlasMap.values()]);
  let sheetW = 0, sheetH = 0;
  for (const f of frames) {
    sheetW = Math.max(sheetW, f.x + f.w);
    sheetH = Math.max(sheetH, f.y + f.h);
  }
  const frameMs = Math.max(10, Math.round(1e3 / fps));
  const frameUris = frames.map((f) => {
    const svg = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${f.w} ${f.h}" width="${f.w}" height="${f.h}">
  <image href="data:image/png;base64,${pngB64}" x="-${f.x}" y="-${f.y}" width="${sheetW}" height="${sheetH}" preserveAspectRatio="none"/>
</svg>`;
    return "data:image/svg+xml;utf8," + encodeURIComponent(svg);
  });
  spriteDataCache.set(kind, { frames, sheetW, sheetH, fps, frameMs, pngBase64: pngB64, frameUris });
}
function getSpriteData(kind) {
  return spriteDataCache.get(kind);
}
var FloatingLabelWidget = class extends import_view.WidgetType {
  constructor(text, color, fontSize, ttl) {
    super();
    this.spanEl = null;
    this.animTimer = null;
    this.text = text;
    this.color = color;
    this.fontSize = fontSize;
    this.ttl = ttl;
    this.createdAt = Date.now();
  }
  toDOM(_view) {
    const wrap = document.createElement("span");
    wrap.className = "rc-widget-container";
    const label = document.createElement("span");
    label.className = "rc-label";
    label.textContent = this.text;
    label.style.color = this.color;
    label.style.fontSize = `${this.fontSize}px`;
    this.spanEl = label;
    wrap.appendChild(label);
    this.startAnimation();
    return wrap;
  }
  startAnimation() {
    const floatEm = 0.7;
    const scaleAdd = 0.6;
    const tick = () => {
      if (!this.spanEl)
        return;
      const now = Date.now();
      const age = now - this.createdAt;
      const progress = Math.max(0, Math.min(1, age / this.ttl));
      const y = -(1.1 + floatEm * progress);
      const s = 1.6 + scaleAdd * progress;
      this.spanEl.style.transform = `translateY(${y}em) scale(${s})`;
      if (progress < 1) {
        this.animTimer = window.setTimeout(tick, 50);
      }
    };
    this.animTimer = window.setTimeout(tick, 50);
  }
  destroy(_dom) {
    if (this.animTimer !== null) {
      window.clearTimeout(this.animTimer);
      this.animTimer = null;
    }
    this.spanEl = null;
  }
};
var IconWidget = class extends import_view.WidgetType {
  constructor(iconName) {
    super();
    this.domEl = null;
    this.iconName = iconName;
  }
  toDOM(view) {
    const wrap = document.createElement("span");
    wrap.className = "rc-widget-container";
    const icon = document.createElement("span");
    icon.className = `rc-icon rc-icon-${this.iconName}`;
    icon.innerHTML = this.getSVG();
    wrap.appendChild(icon);
    this.domEl = wrap;
    return wrap;
  }
  setTransform(y, s) {
    if (this.domEl) {
      this.domEl.style.transform = `translateY(${y}em) scale(${s})`;
    }
  }
  destroy(_dom) {
    this.domEl = null;
  }
  getSVG() {
    switch (this.iconName) {
      case "blip":
        return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 18" width="18" height="18"><circle cx="9" cy="9" r="6" fill="url(#blip-g)" opacity="0.9"/><defs><radialGradient id="blip-g"><stop offset="0%" stop-color="#ff0"/><stop offset="100%" stop-color="#f0f"/></radialGradient></defs></svg>`;
      case "boom":
        return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="24" height="24"><circle cx="16" cy="16" r="14" fill="#ff4400" opacity="0.8"/><circle cx="16" cy="16" r="14" fill="none" stroke="#ffaa00" stroke-width="3" opacity="0.6" transform="scale(0.8) translate(4,4)"/></svg>`;
      case "newline":
        return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 18" width="14" height="14"><path d="M4 4v6h6" fill="none" stroke="#4fc3f7" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/><path d="M10 10L4 4" fill="none" stroke="#4fc3f7" stroke-width="2.5" stroke-linecap="round"/></svg>`;
      default:
        return "";
    }
  }
};
var SpriteIconWidget = class extends import_view.WidgetType {
  constructor(spriteData, kind) {
    super();
    this.currentFrame = 0;
    this.imgEl = null;
    this.domEl = null;
    this.frameTimer = null;
    this.spriteData = spriteData;
    this.kind = kind;
  }
  toDOM(_view) {
    const wrap = document.createElement("span");
    wrap.className = "rc-widget-container";
    const img = document.createElement("img");
    img.className = `rc-icon rc-icon-${this.kind} rc-sprite-icon`;
    img.src = this.spriteData.frameUris[0];
    switch (this.kind) {
      case "blip":
        img.style.width = "18px";
        img.style.height = "18px";
        break;
      case "boom":
        img.style.width = "32px";
        img.style.height = "32px";
        break;
      case "newline":
        img.style.width = "14px";
        img.style.height = "14px";
        break;
    }
    this.imgEl = img;
    wrap.appendChild(img);
    this.domEl = wrap;
    this.startFrameAnim();
    return wrap;
  }
  startFrameAnim() {
    const { frameMs } = this.spriteData;
    const total = this.spriteData.frameUris.length;
    if (total <= 1)
      return;
    const tick = () => {
      if (!this.imgEl || !this.domEl)
        return;
      this.currentFrame++;
      if (this.currentFrame >= total)
        return;
      this.imgEl.src = this.spriteData.frameUris[this.currentFrame];
      this.frameTimer = window.setTimeout(tick, frameMs);
    };
    this.frameTimer = window.setTimeout(tick, frameMs);
  }
  setTransform(y, s) {
    if (this.domEl) {
      this.domEl.style.transform = `translateY(${y}em) scale(${s})`;
    }
  }
  destroy(_dom) {
    if (this.frameTimer !== null) {
      window.clearTimeout(this.frameTimer);
      this.frameTimer = null;
    }
    this.imgEl = null;
    this.domEl = null;
  }
};
var _RidiculousViewPlugin = class {
  constructor(view, settings) {
    this.decorations = import_view.Decoration.none;
    this.pendingEffects = [];
    this.animFrameId = null;
    this.lastBlipTime = 0;
    this.lastBoomTime = 0;
    this.shakeEndAt = 0;
    this.shakeTimerId = null;
    this.shakeDOM = null;
    // Lifetime-tracked overlay system: each batch keeps its own decorations
    this.activeItems = [];
    this.nextId = 0;
    this.animTimers = /* @__PURE__ */ new Map();
    this.view = view;
    this.settings = settings;
  }
  // Color generation matching the Godot original
  static randomGodotColor() {
    const r = Math.min(255, Math.round(Math.random() * 510));
    const g = Math.min(255, Math.round(Math.random() * 510));
    const b = Math.min(255, Math.round(Math.random() * 510));
    return `rgb(${Math.min(255, r)}, ${Math.min(255, g)}, ${Math.min(255, b)})`;
  }
  getEditorFontSizePx() {
    try {
      const cssFontSize = this.view.dom.style.fontSize || getComputedStyle(this.view.dom).fontSize;
      const px = parseFloat(cssFontSize);
      return Math.max(8, isNaN(px) ? 14 : px);
    } catch (e) {
      return 14;
    }
  }
  update(update) {
    if (!update.docChanged)
      return;
    for (const tr of update.transactions) {
      tr.changes.iterChanges(
        (fromA, toA, _fromB, toB, inserted) => {
          const insertedText = inserted.toString();
          const removedLength = toA - fromA;
          if (insertedText.length > 0 && !this.settings.reducedEffects) {
            lastEditWasDelete = false;
            this.handleInsert(toB, insertedText);
          }
          if (removedLength > 0 && !this.settings.reducedEffects) {
            lastEditWasDelete = true;
            this.handleDelete(fromA);
          }
        }
      );
    }
  }
  pendingCount(type) {
    return this.pendingEffects.filter((e) => e.type === type).length;
  }
  handleInsert(pos, text) {
    const now = Date.now();
    if (now - this.lastBlipTime < RATE_LIMITS.BLIP_MS)
      return;
    this.lastBlipTime = now;
    if (text.includes("\n") && this.settings.blips && this.pendingCount("newline") < RATE_LIMITS.MAX_DECORATIONS_PER_TYPE) {
      this.pendingEffects.push({ type: "newline", pos });
    }
    if (this.settings.blips && this.pendingCount("blip") < RATE_LIMITS.MAX_DECORATIONS_PER_TYPE) {
      const charLabel = this.settings.chars ? this.sanitizeLabel(text[0]) : void 0;
      this.pendingEffects.push({ type: "blip", pos, charLabel });
    }
    this.scheduleAnimation();
    if (this.settings.shake) {
      this.triggerShake(text.includes("\n") ? 140 : 120);
    }
  }
  handleDelete(pos) {
    const now = Date.now();
    if (now - this.lastBoomTime < RATE_LIMITS.BOOM_MS)
      return;
    this.lastBoomTime = now;
    if (this.settings.explosions && this.pendingCount("boom") < RATE_LIMITS.MAX_DECORATIONS_PER_TYPE) {
      const charLabel = this.settings.chars ? "BACKSPACE" : void 0;
      this.pendingEffects.push({ type: "boom", pos, charLabel });
    }
    this.scheduleAnimation();
    if (this.settings.shake) {
      this.triggerShake(180);
    }
  }
  scheduleAnimation() {
    if (this.animFrameId !== null)
      return;
    this.animFrameId = window.requestAnimationFrame(() => this.applyEffects());
  }
  rebuildDecorations() {
    const all = [];
    for (const item of this.activeItems) {
      all.push(...item.decorations);
    }
    this.decorations = import_view.Decoration.set(all);
    this.view.dispatch();
  }
  applyEffects() {
    this.animFrameId = null;
    if (this.pendingEffects.length === 0)
      return;
    const typesTriggered = /* @__PURE__ */ new Set();
    for (const effect of this.pendingEffects) {
      const pos = Math.min(effect.pos, this.view.state.doc.length);
      if (pos >= this.view.state.doc.length)
        continue;
      typesTriggered.add(effect.type);
      const cursorPos = pos;
      const itemDecorations = [];
      let iconWidget = null;
      let ttl;
      switch (effect.type) {
        case "blip": {
          ttl = _RidiculousViewPlugin.TRAIL_BLIP_MS;
          const color = _RidiculousViewPlugin.randomGodotColor();
          if (effect.charLabel && this.settings.chars) {
            const widget = new FloatingLabelWidget(effect.charLabel, color, this.getEditorFontSizePx(), ttl);
            itemDecorations.push(
              import_view.Decoration.widget({ widget, side: 1 }).range(cursorPos, cursorPos)
            );
          }
          const blipSprite = getSpriteData("blip");
          if (blipSprite) {
            iconWidget = new SpriteIconWidget(blipSprite, "blip");
          } else {
            iconWidget = new IconWidget("blip");
          }
          itemDecorations.push(
            import_view.Decoration.widget({ widget: iconWidget, side: 1 }).range(cursorPos, cursorPos)
          );
          break;
        }
        case "boom": {
          ttl = _RidiculousViewPlugin.TRAIL_BOOM_MS;
          if (effect.charLabel && this.settings.chars) {
            const color = _RidiculousViewPlugin.randomGodotColor();
            const widget = new FloatingLabelWidget(effect.charLabel, color, this.getEditorFontSizePx(), ttl);
            itemDecorations.push(
              import_view.Decoration.widget({ widget, side: 1 }).range(cursorPos, cursorPos)
            );
          }
          const boomSprite = getSpriteData("boom");
          if (boomSprite) {
            iconWidget = new SpriteIconWidget(boomSprite, "boom");
          } else {
            iconWidget = new IconWidget("boom");
          }
          itemDecorations.push(
            import_view.Decoration.widget({ widget: iconWidget, side: 1 }).range(cursorPos, cursorPos)
          );
          break;
        }
        case "newline": {
          ttl = _RidiculousViewPlugin.TRAIL_NEWLINE_MS;
          const newlineSprite = getSpriteData("newline");
          if (newlineSprite) {
            iconWidget = new SpriteIconWidget(newlineSprite, "newline");
          } else {
            iconWidget = new IconWidget("newline");
          }
          itemDecorations.push(
            import_view.Decoration.widget({ widget: iconWidget, side: -1 }).range(pos, pos)
          );
          break;
        }
      }
      const id = this.nextId++;
      this.activeItems.push({
        id,
        type: effect.type,
        decorations: itemDecorations,
        iconWidget,
        ttl,
        createdAt: Date.now()
      });
    }
    for (const type of typesTriggered) {
      const typeItems = this.activeItems.filter((item) => item.type === type);
      if (typeItems.length > _RidiculousViewPlugin.MAX_TRAIL) {
        const excess = typeItems.length - _RidiculousViewPlugin.MAX_TRAIL;
        const toRemove = typeItems.slice(0, excess);
        this.activeItems = this.activeItems.filter((item) => {
          if (item.type !== type)
            return true;
          return !toRemove.some((r) => r.id === item.id);
        });
      }
    }
    this.rebuildDecorations();
    this.pendingEffects = [];
    for (const type of typesTriggered) {
      this.ensureAnimating(type);
    }
  }
  // ── Per-type continuous frame animation loop ──
  ensureAnimating(type) {
    if (this.animTimers.has(type))
      return;
    const tick = () => {
      const items = this.activeItems.filter((item) => item.type === type);
      if (items.length === 0) {
        const timer = this.animTimers.get(type);
        if (timer) {
          window.clearTimeout(timer);
          this.animTimers.delete(type);
        }
        return;
      }
      const now = Date.now();
      const floatEm = _RidiculousViewPlugin.TRAIL_FLOAT_EM;
      const scaleAdd = _RidiculousViewPlugin.TRAIL_SCALE_ADD;
      const aliveIds = /* @__PURE__ */ new Set();
      for (const item of items) {
        const age = now - item.createdAt;
        const progress = Math.max(0, Math.min(1, age / item.ttl));
        if (progress >= 1)
          continue;
        aliveIds.add(item.id);
        const y = -(1.1 + floatEm * progress);
        const s = 1.6 + scaleAdd * progress;
        if (item.iconWidget) {
          item.iconWidget.setTransform(y, s);
        }
      }
      if (aliveIds.size !== items.length) {
        this.activeItems = this.activeItems.filter((item) => {
          if (item.type !== type)
            return true;
          return aliveIds.has(item.id);
        });
        this.rebuildDecorations();
      }
      this.animTimers.set(type, window.setTimeout(tick, _RidiculousViewPlugin.TRAIL_FRAME_MS));
    };
    this.animTimers.set(type, window.setTimeout(tick, _RidiculousViewPlugin.TRAIL_FRAME_MS));
  }
  // ── Screen Shake ──
  triggerShake(extendMs) {
    if (!this.settings.shake)
      return;
    const now = Date.now();
    const maxEnd = now + RATE_LIMITS.MAX_SHAKE_TOTAL_MS;
    this.shakeEndAt = Math.min(
      Math.max(this.shakeEndAt, now + Math.max(extendMs, this.settings.shakeDecayMs)),
      maxEnd
    );
    if (!this.shakeDOM) {
      this.shakeDOM = this.view.scrollDOM;
    }
    if (this.shakeTimerId === null) {
      this.startShakeLoop();
    }
  }
  startShakeLoop() {
    const tick = () => {
      const now = Date.now();
      if (now >= this.shakeEndAt) {
        this.shakeTimerId = null;
        if (this.shakeDOM) {
          this.shakeDOM.setCssProps({ transform: "" });
        }
        return;
      }
      const amplitude = this.settings.shakeAmplitude;
      const angle = Math.random() * Math.PI * 2;
      const dx = Math.round(Math.cos(angle) * amplitude);
      const dy = Math.round(Math.sin(angle) * amplitude);
      if (this.shakeDOM) {
        this.shakeDOM.setCssProps({
          transform: `translate(${dx}px, ${dy}px)`,
          transition: "transform 0.03s linear"
        });
      }
      this.shakeTimerId = window.setTimeout(tick, RATE_LIMITS.SHAKE_FRAME_MS);
    };
    tick();
  }
  sanitizeLabel(ch) {
    if (ch === "\n")
      return "";
    if (ch === "	")
      return "\u21B9";
    if (ch.trim() === "")
      return "SPACE";
    return ch;
  }
  clearDecorations() {
    for (const [, timer] of this.animTimers) {
      window.clearTimeout(timer);
    }
    this.animTimers.clear();
    this.activeItems = [];
    this.decorations = import_view.Decoration.none;
    this.pendingEffects = [];
    if (this.animFrameId !== null) {
      window.cancelAnimationFrame(this.animFrameId);
      this.animFrameId = null;
    }
    if (this.shakeTimerId !== null) {
      window.clearTimeout(this.shakeTimerId);
      this.shakeTimerId = null;
    }
    if (this.shakeDOM) {
      this.shakeDOM.setCssProps({ transform: "" });
    }
  }
  destroy() {
    this.clearDecorations();
  }
};
var RidiculousViewPlugin = _RidiculousViewPlugin;
// ── Combo trail animation constants ──
RidiculousViewPlugin.TRAIL_BLIP_MS = 400;
RidiculousViewPlugin.TRAIL_BOOM_MS = 650;
RidiculousViewPlugin.TRAIL_NEWLINE_MS = 350;
RidiculousViewPlugin.TRAIL_FRAME_MS = 50;
RidiculousViewPlugin.TRAIL_FLOAT_EM = 0.7;
RidiculousViewPlugin.TRAIL_SCALE_ADD = 0.6;
RidiculousViewPlugin.MAX_TRAIL = 5;
var activeInstances = /* @__PURE__ */ new Set();
function clearActiveDecorations() {
  for (const inst of activeInstances) {
    inst.clearDecorations();
  }
}
function createRidiculousPlugin(settings) {
  class RidiculousPluginAdapter extends RidiculousViewPlugin {
    constructor(view) {
      super(view, settings);
      activeInstances.add(this);
    }
    destroy() {
      super.destroy();
      activeInstances.delete(this);
    }
  }
  return import_view.ViewPlugin.fromClass(RidiculousPluginAdapter, {
    decorations: (p) => p.decorations
  });
}

// src/main.ts
var _RidiculousCodingPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.statusBarItem = null;
    this.pitchIncrease = 0;
    this.pitchResetTimer = null;
    this.oldReducedEffects = false;
  }
  getPanel() {
    var _a, _b;
    return (_b = (_a = this.app.workspace.getLeavesOfType(PANEL_VIEW_TYPE)[0]) == null ? void 0 : _a.view) != null ? _b : null;
  }
  async onload() {
    await this.loadSettings();
    this.xpService = new XPService(this, this.settings.baseXp);
    this.audioService = new AudioService(this.app);
    this.fireworks = new Fireworks();
    await this.audioService.configure();
    try {
      const fontPath = this.app.vault.adapter.getResourcePath(
        `.obsidian/plugins/${PLUGIN_ID}/media/font/GravityBold8.ttf`
      );
      const resp = await (0, import_obsidian5.requestUrl)({ url: fontPath });
      const bytes = new Uint8Array(resp.arrayBuffer);
      let binary = "";
      for (let i = 0; i < bytes.length; i++) {
        binary += String.fromCharCode(bytes[i]);
      }
      setFontBase64(btoa(binary));
    } catch (e) {
      console.warn("Ridiculous Coding: Failed to load font, falling back to monospace");
    }
    try {
      await Promise.all([
        loadSpriteData(this.app, "blip"),
        loadSpriteData(this.app, "boom"),
        loadSpriteData(this.app, "newline")
      ]);
    } catch (e) {
      console.warn("Ridiculous Coding: Failed to load sprite data, falling back to static SVG icons", e);
    }
    this.registerCodeMirrorPlugin();
    this.registerEditorEvents();
    this.statusBarItem = this.addStatusBarItem();
    this.statusBarItem.addClass(STATUS_BAR_CLASS);
    this.statusBarItem.onclick = () => {
      void this.activatePanel();
    };
    this.updateStatusBar();
    this.addRibbonIcon("rocket", "Ridiculous Coding", () => this.activatePanel());
    this.addSettingTab(new RidiculousCodingSettingTab(this.app, this, this.xpService));
    this.registerView(
      PANEL_VIEW_TYPE,
      (leaf) => new RidiculousCodingPanel(
        leaf,
        this.xpService,
        this.settings,
        (key, value) => {
          this.settings[key] = value;
          void this.saveSettings();
        },
        () => {
          this.xpService.reset();
          this.updateStatusBar();
        }
      )
    );
    this.addCommand({
      id: "show-panel",
      name: "Show Panel",
      callback: () => this.activatePanel()
    });
    this.addCommand({
      id: "reset-xp",
      name: "Reset XP",
      callback: () => {
        var _a;
        this.xpService.reset();
        this.updateStatusBar();
        (_a = this.getPanel()) == null ? void 0 : _a.refresh();
      }
    });
    this.oldReducedEffects = this.settings.reducedEffects;
  }
  registerCodeMirrorPlugin() {
    const cmExtension = createRidiculousPlugin(this.settings);
    this.registerEditorExtension(cmExtension);
  }
  registerEditorEvents() {
    this.registerEvent(
      this.app.workspace.on("editor-change", (_editor, _info) => {
        var _a;
        const leveledUp = this.xpService.addXp(1);
        this.updateStatusBar();
        (_a = this.getPanel()) == null ? void 0 : _a.refresh();
        this.pitchIncrease += 1;
        if (this.pitchResetTimer)
          window.clearTimeout(this.pitchResetTimer);
        this.pitchResetTimer = window.setTimeout(
          () => {
            this.pitchIncrease = 0;
          },
          _RidiculousCodingPlugin.PITCH_RESET_MS
        );
        const pitch = 1 + Math.min(20, this.pitchIncrease) * 0.05;
        if (!this.settings.reducedEffects && this.settings.sound) {
          if (wasLastEditDelete()) {
            this.audioService.play({ type: "boom" });
          } else {
            this.audioService.play({ type: "blip", pitch });
          }
        }
        if (leveledUp && !this.settings.reducedEffects && this.settings.fireworks) {
          this.fireworks.show();
          this.audioService.play({ type: "fireworks" });
        }
      })
    );
  }
  async activatePanel() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(PANEL_VIEW_TYPE)[0];
    if (!leaf) {
      const rightLeaf = workspace.getRightLeaf(false);
      if (!rightLeaf)
        return;
      leaf = rightLeaf;
      await leaf.setViewState({ type: PANEL_VIEW_TYPE, active: true });
    }
    workspace.setActiveLeaf(leaf);
  }
  updateStatusBar() {
    if (!this.settings.enableStatusBar || !this.statusBarItem)
      return;
    const prog = this.xpService.progress;
    this.statusBarItem.setText(`RC Lv ${this.xpService.level} \u2014 ${prog.current}/${prog.max} XP`);
    this.statusBarItem.setAttr("aria-label", `Ridiculous Coding - Level ${this.xpService.level}`);
  }
  clearAllDecorations() {
    clearActiveDecorations();
  }
  async loadSettings() {
    const saved = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, saved);
  }
  async saveSettings() {
    var _a;
    await this.saveData(this.settings);
    this.xpService.setBaseXp(this.settings.baseXp);
    this.audioService.isEnabled = this.settings.sound;
    this.updateStatusBar();
    (_a = this.getPanel()) == null ? void 0 : _a.refresh();
    if (!this.oldReducedEffects && this.settings.reducedEffects) {
      this.clearAllDecorations();
    }
    this.oldReducedEffects = this.settings.reducedEffects;
  }
  onunload() {
    this.clearAllDecorations();
    this.audioService.dispose();
    this.fireworks.dispose();
  }
};
var RidiculousCodingPlugin = _RidiculousCodingPlugin;
RidiculousCodingPlugin.PITCH_RESET_MS = 180;
